In [1]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
print('x = ', x) 
print('x has dimensions:', x.shape)
print('The elements in x are of type:', x.dtype)

Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements') 
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

x =  [1 2 3 4 5]
x has dimensions: (5,)
The elements in x are of type: int64
Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


In [ ]:
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)
print(x)

[1 2 3 4 5]


In [ ]:
np.save('my_array', x)

y = np.load('my_array.npy')

print(y)

[1 2 3 4 5]


In [ ]:
X = np.zeros((3,4))
print(X)

In [2]:
X = np.ones((3,2))
print(X)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:
X = np.full((2,3), 5)
print(X)

[[5 5 5]
 [5 5 5]]


In [4]:
X = np.eye(5)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
x= np.array([[1,2,3,] ,[ 10,20,30]])
print(x)
print(x.shape)
print(x.size)
print(x.ndim)

[[ 1  2  3]
 [10 20 30]]
(2, 3)
6
2


In [ ]:
a= [ 1, 2, 3]
b=[ 2,3 ,4]
print(a)
print(b)
c=a+b
print(c)

[1, 2, 3]
[2, 3, 4]
[1, 2, 3, 2, 3, 4]


In [ ]:
import numpy as X
a= X.array( [ 1,2 ,3])
b=X.array([10,20,30])
print(a)
print(b)

c= a+b
d=a-b
e=a*b
f=a/b
print(c)
print(d)
print(e)
print(f)


[1 2 3]
[10 20 30]
[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]


In [ ]:
import numpy as np
A= np.array( [ [10,20, 30], [100,200,300], [1,1,1] ] )
B= np.array( [ [1,1,1], [2,3,3], [4,4,4] ])
print(A)
print(B)
c= A*B;
print(c)

d=A.dot(B)
print(d)

print(A.shape)
print(A.size)


[[ 10  20  30]
 [100 200 300]
 [  1   1   1]]
[[1 1 1]
 [2 3 3]
 [4 4 4]]
[[ 10  20  30]
 [200 600 900]
 [  4   4   4]]
[[ 170  190  190]
 [1700 1900 1900]
 [   7    8    8]]
(3, 3)
9




#Indexing

In [ ]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [ ]:
import numpy as np
A = np.array( [ [1,2,3], [ 5 , 6, 7], [9, 9, 9] ])
print(A)

B= np.array( [[10, 20, 30], [ 20,20,20], [30, 30,30] ])
print(B)
c= A+B
print(c)
print(c.shape)
print(c.size)

[[1 2 3]
 [5 6 7]
 [9 9 9]]
[[10 20 30]
 [20 20 20]
 [30 30 30]]
[[11 22 33]
 [25 26 27]
 [39 39 39]]
(3, 3)
9


In [ ]:
x = np.arange(10)
print(x)
x = np.arange(4,10)
print(x)
x = np.arange(1,14,3)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[ 1  4  7 10 13]


In [ ]:
x = np.linspace(0,25,10)
print(x)

In [ ]:
import numpy as np
x = np.array([[1,2,3,8], [4,5,6,9], [7,8,9,3], [10, 11, 12,8]])
print(x)
print(x.shape)
print(np.reshape(x, (2,8)))
print(np.reshape(x,[16,1]))
x

[[ 1  2  3  8]
 [ 4  5  6  9]
 [ 7  8  9  3]
 [10 11 12  8]]
(4, 4)
[[ 1  2  3  8  4  5  6  9]
 [ 7  8  9  3 10 11 12  8]]
[[ 1]
 [ 2]
 [ 3]
 [ 8]
 [ 4]
 [ 5]
 [ 6]
 [ 9]
 [ 7]
 [ 8]
 [ 9]
 [ 3]
 [10]
 [11]
 [12]
 [ 8]]


array([[ 1,  2,  3,  8],
       [ 4,  5,  6,  9],
       [ 7,  8,  9,  3],
       [10, 11, 12,  8]])

In [ ]:
# reshape
x = np.array([[1,2,3,8], [4,5,6,9], [7,8,9,3], [10, 11, 12,8]])
print(x)
# total 12 elements, all factors of 12 can be possible
print(np.reshape(x, (2, 8))) 
print(np.reshape(x, (8, 2))) 
#print(np.reshape(x, (2, 6)))

[[ 1  2  3  8]
 [ 4  5  6  9]
 [ 7  8  9  3]
 [10 11 12  8]]
[[ 1  2  3  8  4  5  6  9]
 [ 7  8  9  3 10 11 12  8]]
[[ 1  2]
 [ 3  8]
 [ 4  5]
 [ 6  9]
 [ 7  8]
 [ 9  3]
 [10 11]
 [12  8]]


In [ ]:
import numpy as np
e = np.random.random((2,5,2))
print(e)

[[[0.27611791 0.20553522]
  [0.57737752 0.53703416]
  [0.38029772 0.88664182]
  [0.99863706 0.8004904 ]
  [0.29920016 0.25038848]]

 [[0.72752863 0.4330491 ]
  [0.8866925  0.67850489]
  [0.85993522 0.10003242]
  [0.08052407 0.35052201]
  [0.94077498 0.86144401]]]


In [12]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
#print(a[:,:])
print(a[:,3])
print(a[:,2])
print(a[:,:3])
print(a[:2,:2])
print(a[1:3, 1:3])

print()

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 4  8 12]
[ 3  7 11]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[1 2]
 [5 6]]
[[ 6  7]
 [10 11]]



In [ ]:
# Integer indexing VS slice indexing

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
print(a.shape)
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:3, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"

print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)

(3, 4)
[5 6 7 8] (4,)
[[ 5  6  7  8]
 [ 9 10 11 12]] (2, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
# Boolean array indexing

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [ ]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print(a[:3, :4])
#print(a[:1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
x = np.arange(20)
print(x)
x = np.reshape(x, (4,5))
print(x)
x = np.arange(20).reshape(4, 5) 
print(x)
y = np.linspace(0,50,10, endpoint=False).reshape(5,2)
print(y)


In [ ]:
X = np.random.random((3,3))
print(X)

In [ ]:
# max/ min

a= np.array([[1,2], [3, 4], [5, 6]])
print(a)
print(a.ndim)
print(a.min())
print(a.max())
print(a.sum())
print(a.cumsum())

[[1 2]
 [3 4]
 [5 6]]
2
1
6
21
[ 1  3  6 10 15 21]


In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))
# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))
print(x*2)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2. 4.]
 [6. 8.]]


In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
print(x)
print(np.sqrt(x))
print(x*2)

[[1. 2.]
 [3. 4.]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2. 4.]
 [6. 8.]]


In [ ]:
# Matrix multiplication is carried out by dot function
# dot is available both as a function in the numpy module and as an instance method of array objects

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)

v = np.array([9,10])
w = np.array([11, 12])
print(v)
print(w)

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[ 9 10]
[11 12]
219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
# transpose

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [ ]:
x = np.array([1, 2, 3, 4, 5])
print(x)
x = np.delete(x, [0,4])
print(x)
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(Y)
w = np.delete(Y, 0, axis=0)
print(w)
v = np.delete(Y, [0,2], axis=1)
print(v)

[1 2 3 4 5]
[2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[2]
 [5]
 [8]]


In [ ]:
# Broadcasting
# Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
print(x)
print(v)
y = np.empty_like(x)   # Create an empty matrix with the same shape as x
print(y)

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v
# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
x = np.append(x, 6)
print(x)
x = np.append(x, [7,8])
print(x)
v = np.append(Y, [[10,11,12]], axis=0)
print(v)
q = np.append(Y,[[13],[14],[15]], axis=1)
print(q)

In [ ]:
x = np.array([1, 2, 5, 6, 7])
print(x)
Y = np.array([[1,2,3],[7,8,9]])
print(Y)
x = np.insert(x,2,[3,4])
print(x)
w = np.insert(Y,1,[4,5,6],axis=0)
print(w)
v = np.insert(Y,1,5, axis=1)
print(v)

In [ ]:
x = np.array([1,2])
print(x)
Y = np.array([[3,4],[5,6]])
print(Y)
z = np.vstack((x,Y))
print(z)
w = np.hstack((Y,x.reshape(2,1)))
print(w)

In [ ]:
Z = np.copy(X[1:4,2:5])
print(Z)
W = X[1:4,2:5].copy()
print(w)

In [ ]:
u = np.unique(X)
print(u)

In [ ]:
X = np.arange(25).reshape(5, 5)
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])
X[(X > 10) & (X < 17)] = -1

In [ ]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))

In [ ]:
s = np.sort(x)
x.sort()
print(x)
s = np.sort(np.unique(x))
print(s)
s = np.sort(X, axis = 0)
print(s)
s = np.sort(X, axis = 1)
print(s)

In [ ]:
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

In [ ]:
np.add(x,y)

In [ ]:
np.subtract(x,y)

In [ ]:
np.multiply(x,y)


In [ ]:
np.divide(x,y)

In [ ]:
np.exp(x)

In [ ]:
np.sqrt(x)

In [ ]:
np.power(x,2)

In [ ]:
print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Standard Deviation of all elements in X:', X.std())
print('Median of all elements in X:', np.median(X))
print('Maximum value of all elements in X:', X.max())
print('Minimum value of all elements in X:', X.min())

In [ ]:
print(4*X)
print(4+X)
print(4-X)

# Pandas

In [ ]:
import pandas as pd
groceries = pd.Series(data = [30, 6, 'Yes', 'No'], index = ['eggs', 'apples', 'milk', 'bread'])
print('Groceries has shape:', groceries.shape)
print('Groceries has dimension:', groceries.ndim)
print('Groceries has a total of', groceries.size, 'elements')
print('The data in Groceries is:', groceries.values)
print('The index of Groceries is:', groceries.index)

In [ ]:
print('How many eggs do we need to buy:', groceries['eggs'])
print('Do we need milk and bread:\n', groceries[['milk', 'bread']]) 
print('How many eggs and apples do we need to buy:\n', groceries.loc[['eggs', 'apples']]) 

print('How many eggs and apples do we need to buy:\n',  groceries[[0, 1]]) 
print('Do we need bread:\n', groceries[[-1]]) 
print('How many eggs do we need to buy:', groceries[0]) 
print('Do we need milk and bread:\n', groceries.iloc[[2, 3]])

In [ ]:
groceries['eggs'] = 2
groceries.drop('apples')
groceries.drop('apples', inplace = True)
fruits = pd.Series(data = [10, 6, 3,], index = ['apples', 'oranges', 'bananas'])
fruits + 2
fruits - 2
fruits * 2
fruits / 2
np.exp(fruits)
np.sqrt(fruits)
np.power(fruits,2)
fruits['bananas'] + 2
fruits.iloc[0] - 2
fruits[['apples', 'oranges']] * 2

In [ ]:
Matplotlib

In [ ]:
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
import numpy as np

In [ ]:
fig = plt.figure()
ax = plt.axes()

In [ ]:
fig = plt.figure()
ax = plt.axes()

x = np.linspace(0, 10, 1000)
ax.plot(x, np.sin(x));

In [ ]:
plt.plot(x, np.sin(x));

In [ ]:
plt.plot(x, np.sin(x))
plt.plot(x, np.cos(x));

In [ ]:
plt.plot(x, np.sin(x - 0), color='blue')        
plt.plot(x, np.sin(x - 1), color='g')           
plt.plot(x, np.sin(x - 2), color='0.75')        
plt.plot(x, np.sin(x - 3), color='#FFDD44')     
plt.plot(x, np.sin(x - 4), color=(1.0,0.2,0.3)) 
plt.plot(x, np.sin(x - 5), color='chartreuse');

In [ ]:
plt.plot(x, x + 0, linestyle='solid')
plt.plot(x, x + 1, linestyle='dashed')
plt.plot(x, x + 2, linestyle='dashdot')
plt.plot(x, x + 3, linestyle='dotted');


plt.plot(x, x + 4, linestyle='-')  
plt.plot(x, x + 5, linestyle='--') 
plt.plot(x, x + 6, linestyle='-.') 
plt.plot(x, x + 7, linestyle=':'); 

In [ ]:
plt.plot(x, x + 0, '-g')  # solid green
plt.plot(x, x + 1, '--c') # dashed cyan
plt.plot(x, x + 2, '-.k') # dashdot black
plt.plot(x, x + 3, ':r');  # dotted red

In [ ]:
plt.plot(x, np.sin(x))

plt.xlim(-1, 11)
plt.ylim(-1.5, 1.5);


In [ ]:
plt.plot(x, np.sin(x))

plt.xlim(10, 0)
plt.ylim(1.2, -1.2);

In [ ]:
plt.plot(x, np.sin(x))
plt.axis([-1, 11, -1.5, 1.5]);


In [ ]:
plt.plot(x, np.sin(x))
plt.axis('tight');

In [ ]:
plt.plot(x, np.sin(x))
plt.axis('equal');

In [ ]:
plt.plot(x, np.sin(x))
plt.title("A Sine Curve")
plt.xlabel("x")
plt.ylabel("sin(x)");


In [ ]:
plt.plot(x, np.sin(x), '-g', label='sin(x)')
plt.plot(x, np.cos(x), ':b', label='cos(x)')
plt.axis('equal')

plt.legend();

In [ ]:
ax = plt.axes()
ax.plot(x, np.sin(x))
ax.set(xlim=(0, 10), ylim=(-2, 2),
       xlabel='x', ylabel='sin(x)',
       title='A Simple Plot');